#!/bin/bash
export LANG=C
REPOPATH="$HOME/.mnju"
REPOURL="https://github.com/manjaro"
REPONAMES="packages-community packages-core packages-extra"
if [ ! -d "$REPOPATH" ]; then
    mkdir -p "$REPOPATH"
fi
if [ ! -e "$REPOPATH/.LOCK" ]; then
    touch "$REPOPATH/.LOCK"
    cd $REPOPATH
    for i in $REPONAMES
        do
            git clone "$REPOURL/$i.git"
    done
else
    for i in $REPONAMES
        do
            cd "$REPOPATH/$i" && git pull
    done
    rm -f $REPOPATH/20*
    tree > "$REPOPATH/20$(date +%y%m%d).TREE"
    ls -lah --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F $REPOPATH/packages* > "$REPOPATH/20$(date +%y%m%d).DIRS"
fi
